from flask_sqlalchemy import SQLAlchemy

from sqlalchemy import Column, Float, Integer, String
from typing import Callable


class MySQLAlchemy(SQLAlchemy):
    Column: Callable
    String: Callable
    Integer: Callable
    Boolean: Callable


db = SQLAlchemy()


class Data(db.Model):
    __tablename__ = 'data'
    id = Column(Integer, primary_key=True)
    edu_index = Column(Float, nullable=True)
    science_index = Column(Float, nullable=True)
    inter_index = Column(Float, nullable=True)
    fin_index = Column(Float, nullable=True)
    wage = Column(Float, nullable=True)
    add = Column(Float, nullable=True)
    exam_1 = Column(Float, nullable=True)
    exam_2 = Column(Float, nullable=True)
    exam_3 = Column(Float, nullable=True)
    avg_exam_1 = Column(Float, nullable=True)
    stud_num_1 = Column(Float, nullable=True)
    stud_num_2 = Column(Float, nullable=True)
    stud_num_3 = Column(Float, nullable=True)
    w_1 = Column(Float, nullable=True)
    w_2 = Column(Float, nullable=True)
    w_3 = Column(Float, nullable=True)
    w_4 = Column(Float, nullable=True)
    w_5 = Column(Float, nullable=True)
    asp_num = Column(Float, nullable=True)
    w_6 = Column(Float, nullable=True)
    w_7 = Column(Float, nullable=True)
    citation_1 = Column(Float, nullable=True)
    citation_2 = Column(Float, nullable=True)
    citation_3 = Column(Float, nullable=True)
    pub_num_1 = Column(Float, nullable=True)
    pub_num_2 = Column(Float, nullable=True)
    pub_num_3 = Column(Float, nullable=True)
    research_num = Column(Float, nullable=True)
    w_8 = Column(Float, nullable=True)
    w_9 = Column(Float, nullable=True)
    research_incom = Column(Float, nullable=True)
    license_num = Column(Float, nullable=True)
    w_10 = Column(Float, nullable=True)
    w_11 = Column(Float, nullable=True)
    w_12 = Column(Float, nullable=True)
    journal_num = Column(Float, nullable=True)
    grants_num = Column(Float, nullable=True)
    w_13 = Column(Float, nullable=True)
    w_14 = Column(Float, nullable=True)
    w_15 = Column(Float, nullable=True)
    w_16 = Column(Float, nullable=True)
    w_17 = Column(Float, nullable=True)
    w_18 = Column(Float, nullable=True)
    stud_num_4 = Column(Float, nullable=True)
    w_19 = Column(Float, nullable=True)
    prof_num = Column(Float, nullable=True)
    w_20 = Column(Float, nullable=True)
    w_21 = Column(Float, nullable=True)
    money_1 = Column(Float, nullable=True)
    money_2 = Column(Float, nullable=True)
    income_per_npr = Column(Float, nullable=True)
    w_22 = Column(Float, nullable=True)
    avg_wage_1 = Column(Float, nullable=True)
    total_income = Column(Float, nullable=True)
    total_square_1 = Column(Float, nullable=True)
    square_1 = Column(Float, nullable=True)
    square_2 = Column(Float, nullable=True)
    square_3 = Column(Float, nullable=True)
    square_4 = Column(Float, nullable=True)
    computer_number = Column(Float, nullable=True)
    w_23 = Column(Float, nullable=True)
    books = Column(Float, nullable=True)
    w_24 = Column(Float, nullable=True)
    w_25 = Column(Float, nullable=True)
    w_26 = Column(Float, nullable=True)
    npr_num = Column(Float, nullable=True)
    w_27 = Column(Float, nullable=True)
    total_stud_num_1 = Column(Float, nullable=True)
    stud_num_5 = Column(Float, nullable=True)
    stud_num_6 = Column(Float, nullable=True)
    stud_num_7 = Column(Float, nullable=True)
    avg_exam_2 = Column(Float, nullable=True)
    w_28 = Column(Float, nullable=True)
    w_29 = Column(Float, nullable=True)
    w_30 = Column(Float, nullable=True)
    stud_num_8 = Column(Float, nullable=True)
    stud_num_9 = Column(Float, nullable=True)
    company_num_1 = Column(Float, nullable=True)
    company_num_2 = Column(Float, nullable=True)
    money_3 = Column(Float, nullable=True)
    money_4 = Column(Float, nullable=True)
    total_pub_num = Column(Float, nullable=True)
    bi_num = Column(Float, nullable=True)
    tp_num = Column(Float, nullable=True)
    ccus_num = Column(Float, nullable=True)
    sb_num = Column(Float, nullable=True)
    total_asp_num = Column(Float, nullable=True)
    w_31 = Column(Float, nullable=True)
    total_doc_num = Column(Float, nullable=True)
    diss_sov_num = Column(Float, nullable=True)
    total_work_num = Column(Float, nullable=True)
    total_pps_num = Column(Float, nullable=True)
    total_sci_num = Column(Float, nullable=True)
    w_32 = Column(Float, nullable=True)
    w_33 = Column(Float, nullable=True)
    w_34 = Column(Float, nullable=True)
    w_35 = Column(Float, nullable=True)
    avg_wage_2 = Column(Float, nullable=True)
    avg_wage_3 = Column(Float, nullable=True)
    for_stud_num = Column(Float, nullable=True)
    w_36 = Column(Float, nullable=True)
    total_prog_num = Column(Float, nullable=True)
    total_stud_num_2 = Column(Float, nullable=True)
    total_for_asp_num = Column(Float, nullable=True)
    citation_4 = Column(Float, nullable=True)
    for_income_1 = Column(Float, nullable=True)
    for_income_2 = Column(Float, nullable=True)
    results_num = Column(Float, nullable=True)
    total_square_2 = Column(Float, nullable=True)
    lab_square = Column(Float, nullable=True)
    research_square = Column(Float, nullable=True)
    living_square = Column(Float, nullable=True)
    sport_square = Column(Float, nullable=True)
    w_37 = Column(Float, nullable=True)
    comp_num = Column(Float, nullable=True)
    w_38 = Column(Float, nullable=True)
    library = Column(Float, nullable=True)
    income = Column(Float, nullable=True)
    non_budget_income = Column(Float, nullable=True)
    w_39 = Column(Float, nullable=True)
    w_40 = Column(Float, nullable=True)
    w_41 = Column(Float, nullable=True)
    w_42 = Column(Float, nullable=True)
    w_43 = Column(Float, nullable=True)
    w_44 = Column(Float, nullable=True)
    w_45 = Column(Float, nullable=True)


class Info(db.Model):
    __tablename__ = 'info'
    id = Column(Integer, primary_key=True)
    var_name = Column(String, nullable=True)
    var_description = Column(String, nullable=True)
