########################
# DEFAULT CONFIGURATION
########################

# General
DEBUG: True
SEED: 36

UPDATE_DATA: True
DATA_PATH:
SQLALCHEMY_DATABASE: postgresql://postgres:postgres@localhost:5432/MLOps

MODEL_PARAMETERS_PATH:

STORAGE_PATH:

PREDICTIONS_PATH:

ESTIMATED_MODELS_PATH:

